### ISSUE TITLE
Incompatibility with optifabric

### ISSUE THREAD

**Issue by bisquickpancakemix** [MrCrayfish/Controllable#397] opened 2023-05-08 03:02 UTC
The mouse cursor doesn't work at all with optifabric, this mod is not compatible with optifabric it seems. The cursor disappears and is invisible. Uninstalling only optifine and changing nothing else brings it back.

**Comment by MrCrayfish** [comment] 2023-05-08 10:24
Won't fix. Please use alternatives, Optifine is known to cause issues with mods, not just my own.

**Closed as completed by MrCrayfish** 2023-05-08 10:24 UTC

**Comment by bisquickpancakemix** [comment] 2023-05-08 15:48
i cant, optifine provides me better performance on my specific hardware than sodium and quite a few extra optimzation mods combined, plus i just tried sodium with a new config and it just crashes my game. but thanks

**Comment by MrCrayfish** [comment] 2023-05-09 03:10
I'll look into it when I end up working on another update, it's just not a super priority. The problem is Optifine changes the rendering pipeline and creates oddities, which such has broken the virtual cursor rendering.

**Comment by bisquickpancakemix** [comment] 2023-05-09 13:25
i understand, thanks for taking the time to explain the issue. ive got sodium working and the cursor works fine now !

**Comment by DataNinja100** [comment] 2023-10-13 21:01
I also have a problem, my game just crashes and doesn't even open, I have optifabric and controllable.
Is this fixable?
