### ISSUE TITLE
not working with xbox one controllers

### ISSUE THREAD

**Issue by rydellwipf** [MrCrayfish/Controllable#387] opened 2023-04-09 08:11 UTC
having difficulties getting the curser to move smoothly its incredibly jumpy and not fluid ive messed with every setting and i can get it to work a bit better but to were its enjoyable to even play the game, i absolutely love this mod but at this point im just not going to play minecraft java due to no controller support i cant stand playing with a key board i dont know how to add a video on how to show whats going on

if you barely touch the right thumbstick the screen spins way way to fast like its on speed

**Comment by MrCrayfish** [comment] 2023-04-10 14:52
Sounds to me like a double input issue, this is caused by Steam. All you need to do is close steam and the issue should be fixed. Otherwise check out the documentation for guides and troubleshooting: https://mrcrayfish.gitbook.io/controllable-documentation/

**Closed as completed by MrCrayfish** 2023-04-10 14:52 UTC
