### ISSUE TITLE
Switch Pro Controller Issue

### ISSUE THREAD

**Issue by sjk210** [MrCrayfish/Controllable#58] opened 2020-01-14 04:42 UTC
When I use the Nintendo Switch Pro Controller, I am not able to sprint and my walking speed is decreased slightly. Every other input works perfectly.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment] 2020-10-03 16:58
it means the stick is off-center when you connect it, it happens

**Comment by NR67** [comment] 2021-03-02 17:26
The problem is that the mod is just not compatible with the Nintendo Switch Pro Controller. If you try to connect the controller to something not made by Nintendo, Example: PS3. You will notice that the left joystick have issues. The controller just doesnt work the same way than most controllers do.

**Comment by MrCrayfish** [comment] 2023-04-10 06:46
I've recently written some guides on different methods of connecting controllers and troubleshooting issues. In this particular case, I recommend checking out the DS4Windows or GlosSI method. I am closing this issue due it being quite old and most likely resolved reading the guides.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad

**Closed by MrCrayfish** 2023-04-10 06:46 UTC
Labels: gamepad
