### ISSUE TITLE
Switch Pro controller not working

### ISSUE THREAD

**Issue by Nawako0** [MrCrayfish/Controllable#151] opened 2021-02-10 19:14 UTC
When using Bluetooth, my controller gets detected but does nothing, when wired it's like every input get done at once.

**Comment by Sigmania** [comment] 2021-02-10 20:13
Update: Steam controller configuration might've been the problem. After closing Steam entirely with Task Manager and unpairing and pairing my controller, it doesn't go crazy when wired anymore, it just does nothing at all.

**Comment by Sigmania** [comment] 2021-02-10 20:24
Update 2: It finally woks! I think all I had to do was unwire it and only use Bluetooth. The camera is a bit too slow and I move slower than normal for some strange reason? I'm gonna figure that out.

**Comment by Sigmania** [comment] 2021-02-10 20:29
Update 3: I found the problem... kinda... So when the green Player 1 light and the blue circle around the HOME button are on it means it just won't work, no input will be taken. I'm just not sure how the lights are triggered or how to enter that mode where it works.

**Comment by Sigmania** [comment] 2021-02-10 20:49
Update 4: The situation has returned to wht it was at the beggining but this time the blue circle isn't on

**Comment by Sigmania** [comment] 2021-02-10 20:55
Update 5: After closing the Steam Client Bootstrapper, it looks like it's working! I think the problem is that if anything, and I mean ANYTHING else is taking input from the controller it won't work. So if you have JoyToKey, Steam, reWASD and other things like that, close them via Task Manager, unsync and sync your Pro Controller and it *should* work. But that's just a theory... A GAM- sorry

**Comment by Sigmania** [comment] 2021-02-10 20:56
Also is there any way of swaping A and B like you can already do on console?

**Comment by MrCrayfish** [comment] 2023-04-10 06:58
You can now use Switch Pro Controller using either DS4Windows or GlosSI. You can read the guides here:
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad

**Closed by MrCrayfish** 2023-04-10 06:58 UTC
Labels: gamepad
